version: ~> 1.0

env:
  global:
    - COMPOSER_ROOT_VERSION=2.x-dev
    - $REQUIRE_RECIPE="4.x-dev"

import:
  - silverstripe/silverstripe-travis-shared:config/provision/cwp.yml

# TODO: With 2.7 onwards, remove custom jobs matrix and provision with cwp-jobs-fixed.yml
jobs:
  include:
    - php: 7.1
      env:
        - DB=MYSQL
        - REQUIRE_RECIPE_CMS="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
    - php: 7.2
      env:
        - DB=MYSQL
        - REQUIRE_RECIPE_CMS="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
    - php: 7.3
      env:
        - DB=MYSQL
        - REQUIRE_RECIPE_CMS="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_RECIPE_CMS="$REQUIRE_RECIPE"
        - PHPUNIT_COVERAGE_TEST=1
